[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bskytui"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["atproto", "textual", "pydantic-settings"]

[tool.hatch.metadata]
allow-direct-references = true
